use crate::crypto::ParticipantId;
use crate::crypto::SecretScalar;
use crate::errors::FrostError;
use crate::errors::Result;
use secp256k1::PublicKey;
use secp256k1::XOnlyPublicKey;
use secp256k1::Secp256k1;
use secp256k1::rand::thread_rng;
use vsss_rs::*;
use vsss_rs::shamir::*;
use zeroize::Zeroizing;

/// A participant in the FROST protocol.
#[derive(Debug, Clone)]
pub struct Participant {
    id: ParticipantId,
    threshold: usize,
    n: usize,
    sk: Option<Zeroizing<SecretScalar>>,
    public_key: Option<XOnlyPublicKey>,
    dkg_state: DkgState,
}

/// Internal DKG state.
#[derive(Debug, Clone)]
enum DkgState {
    Initialized,
    Round1Complete(Round1Data),
    Round2Complete(Round2Data),
    Completed(DistributedKey),
}

/// Round 1 data generated by a participant.
#[derive(Debug, Clone)]
pub struct Round1Output {
    pub participant_id: ParticipantId,
    pub commitments: Vec<PublicKey>,
    pub proof: Vec<u8>,
}

/// Round 2 data generated by a participant.
#[derive(Debug, Clone)]
pub struct Round2Output {
    pub participant_id: ParticipantId,
    pub shares: Vec<(ParticipantId, Vec<u8>)>,
    pub verification_shares: Vec<PublicKey>,
}

/// A participant's share of the distributed key.
#[derive(Debug, Clone)]
pub struct DistributedKey {
    pub participant_id: ParticipantId,
    sk_share: Zeroizing<SecretScalar>,
    pub public_key: XOnlyPublicKey,
    pub verification_shares: Vec<PublicKey>,
}

impl Participant {
    /// Creates a new participant.
    pub fn new(id: ParticipantId, threshold: usize, n: usize) -> Result<Self> {
        if n < 2 {
            return Err(FrostError::InvalidParticipantCount);
        }
        if threshold < 1 || threshold >= n {
            return Err(FrostError::InvalidThreshold);
        }

        Ok(Self {
            id,
            threshold,
            n,
            sk: None,
            public_key: None,
            dkg_state: DkgState::Initialized,
        })
    }

    /// Returns the participant's ID.
    pub fn id(&self) -> ParticipantId {
        self.id
    }

    /// Performs round 1 of DKG.
    pub fn dkg_round1(&mut self) -> Result<Round1Output> {
        let secp = Secp256k1::new();
        
        // Generate random secret scalar for this participant
        let sk = Zeroizing::new(SecretScalar::random());
        
        // Generate a polynomial for secret sharing
        let coefficients = (0..self.threshold)
            .map(|_| {
                let scalar = SecretScalar::random();
                PublicKey::from_secret_key(&secp, scalar.as_inner())
            })
            .collect::<Vec<_>>();

        // Store the secret key and commitments
        self.sk = Some(sk);
        self.dkg_state = DkgState::Round1Complete(Round1Data { coefficients });

        Ok(Round1Output {
            participant_id: self.id,
            commitments: coefficients,
            proof: vec![0], // Simplified proof
        })
    }

    /// Performs round 2 of DKG.
    pub fn dkg_round2(&mut self, round1_inputs: &[Round1Output]) -> Result<Round2Output> {
        let Round1Data { coefficients } = match &self.dkg_state {
            DkgState::Round1Complete(data) => data,
            _ => return Err(FrostError::InvalidDkgRound1Commitments),
        };

        // Verify all round 1 commitments
        if round1_inputs.len() != self.n {
            return Err(FrostError::InvalidDkgRound1Commitments);
        }

        // Generate shares for all participants using Shamir's secret sharing
        let sk = self.sk.as_ref().ok_or(FrostError::RngError)?;
        let shares = self.generate_shares(sk);

        // Store round 2 state
        self.dkg_state = DkgState::Round2Complete(Round2Data { shares: shares.clone() });

        Ok(Round2Output {
            participant_id: self.id,
            shares: shares.iter()
                .map(|(id, share)| (*id, share.to_bytes().to_vec()))
                .collect(),
            verification_shares: coefficients.clone(),
        })
    }

    /// Completes the DKG process.
    pub fn complete_dkg(&mut self, round2_inputs: &[Round2Output]) -> Result<DistributedKey> {
        let Round2Data { shares: my_shares } = match &self.dkg_state {
            DkgState::Round2Complete(data) => data,
            _ => return Err(FrostError::InvalidDkgRound2Shares),
        };

        // Verify all round 2 outputs
        if round2_inputs.len() != self.n {
            return Err(FrostError::InvalidDkgRound2Shares);
        }

        // Collect all shares from other participants
        let mut all_shares = Vec::new();
        for output in round2_inputs {
            // Find the share for this participant
            if let Some(share) = output.shares.iter().find(|(id, _)| *id == self.id) {
                all_shares.push((output.participant_id, share.1.clone()));
            }
        }

        // Combine shares to form the distributed key
        let combined_share = self.combine_shares(&all_shares)?;

        // Compute the aggregated public key
        let aggregated_pk = self.compute_aggregated_pk(round2_inputs);

        let distributed_key = DistributedKey {
            participant_id: self.id,
            sk_share: Zeroizing::new(combined_share),
            public_key: aggregated_pk,
            verification_shares: round2_inputs
                .iter()
                .flat_map(|o| o.verification_shares.clone())
                .collect(),
        };

        self.dkg_state = DkgState::Completed(distributed_key.clone());
        Ok(distributed_key)
    }

    /// Generates shares for all participants using Shamir's secret sharing.
    fn generate_shares(&self, sk: &Zeroizing<SecretScalar>) -> Vec<(ParticipantId, SecretScalar)> {
        let mut shares = Vec::with_capacity(self.n);
        let coeffs = vec![sk.to_bytes()];

        for i in 0..self.n {
            let id = ParticipantId(i as u64);
            let share = self.evaluate_polynomial(&coeffs, id.0 as u8);
            shares.push((id, SecretScalar::from_bytes(&share).unwrap()));
        }

        shares
    }

    /// Evaluates a polynomial at a given point.
    fn evaluate_polynomial(&self, coeffs: &[[u8; 32]], x: u8) -> [u8; 32] {
        // Simplified polynomial evaluation (using mod 2^256)
        let mut result = [0u8; 32];
        
        for (i, coeff) in coeffs.iter().enumerate() {
            let mut term = coeff.clone();
            let xi = x as u64;
            
            for _ in 0..i {
                term = self.scalar_multiply(&term, &(xi.to_le_bytes()[..32]));
            }
            
            result = self.scalar_add(&result, &term);
        }
        
        result
    }

    /// Combines shares to form the secret.
    fn combine_shares(&self, shares: &[(ParticipantId, Vec<u8>)]) -> Result<SecretScalar> {
        if shares.len() < self.threshold {
            return Err(FrostError::NotEnoughShares {
                expected: self.threshold,
                got: shares.len(),
            });
        }

        // Verify shares have correct length
        for (_, share) in shares {
            if share.len() != 32 {
                return Err(FrostError::InvalidDkgRound2Shares);
            }
        }

        // Simplified share combination
        let mut combined = [0u8; 32];
        
        for (i, (id, share)) in shares.iter().enumerate() {
            let share_bytes: [u8; 32] = share.as_slice().try_into()
                .map_err(|_| FrostError::InvalidDkgRound2Shares)?;
                
            let mut term = share_bytes;
            
            // Compute Lagrange coefficient (simplified)
            for (j, (other_id, _)) in shares.iter().enumerate() {
                if i != j {
                    let num = other_id.0;
                    let den = (other_id.0 - id.0) as i64;
                    let coeff = (num as i64) * den.signum() / den.abs();
                    
                    term = self.scalar_multiply(&term, &(coeff as u64).to_le_bytes()[..32]);
                }
            }
            
            combined = self.scalar_add(&combined, &term);
        }
        
        Ok(SecretScalar::from_bytes(&combined)?)
    }

    /// Computes the aggregated public key.
    fn compute_aggregated_pk(&self, round2_inputs: &[Round2Output]) -> XOnlyPublicKey {
        let secp = Secp256k1::new();
        let mut aggregated = PublicKey::from_secret_key(&secp, &secp256k1::SecretKey::from_slice(&[0u8; 32]).unwrap());
        
        for output in round2_inputs {
            for (i, vk) in output.verification_shares.iter().enumerate() {
                if i == 0 {
                    aggregated = aggregated.combine(vk).unwrap_or(aggregated);
                }
            }
        }
        
        let (xonly, _) = XOnlyPublicKey::from_keypair(&secp, &secp256k1::Keypair::from(
            secp256k1::SecretKey::from_slice(&[0u8; 32]).unwrap()
        ));
        
        xonly
    }

    /// Simple scalar multiplication (mod 2^256).
    fn scalar_multiply(&self, a: &[u8; 32], b: &[u8; 32]) -> [u8; 32] {
        let a_u64 = u64::from_le_bytes(a[0..8].try_into().unwrap());
        let b_u64 = u64::from_le_bytes(b[0..8].try_into().unwrap());
        let result_u64 = (a_u64 * b_u64) % (1 << 64);
        let mut result = [0u8; 32];
        result[0..8].copy_from_slice(&result_u64.to_le_bytes());
        result
    }

    /// Simple scalar addition (mod 2^256).
    fn scalar_add(&self, a: &[u8; 32], b: &[u8; 32]) -> [u8; 32] {
        let a_u64 = u64::from_le_bytes(a[0..8].try_into().unwrap());
        let b_u64 = u64::from_le_bytes(b[0..8].try_into().unwrap());
        let result_u64 = (a_u64 + b_u64) % (1 << 64);
        let mut result = [0u8; 32];
        result[0..8].copy_from_slice(&result_u64.to_le_bytes());
        result
    }
}

impl DistributedKey {
    /// Returns the participant's secret share.
    pub fn secret_share(&self) -> &[u8; 32] {
        &self.sk_share.to_bytes()
    }

    /// Returns the public key.
    pub fn public_key(&self) -> XOnlyPublicKey {
        self.public_key
    }
}

/// Internal DKG round 1 data.
#[derive(Debug, Clone)]
struct Round1Data {
    coefficients: Vec<PublicKey>,
}

/// Internal DKG round 2 data.
#[derive(Debug, Clone)]
struct Round2Data {
    shares: Vec<(ParticipantId, SecretScalar)>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_participant_creation() {
        let participant = Participant::new(ParticipantId(0), 3, 5).unwrap();
        assert_eq!(participant.id(), ParticipantId(0));
    }

    #[test]
    fn test_dkg_basic_flow() {
        // Initialize participants
        let mut participants = Vec::new();
        for i in 0..5 {
            participants.push(Participant::new(ParticipantId(i), 3, 5).unwrap());
        }

        // Round 1
        let round1_outputs: Vec<_> = participants.iter_mut()
            .map(|p| p.dkg_round1().unwrap())
            .collect();

        // Round 2
        let round2_outputs: Vec<_> = participants.iter_mut()
            .map(|p| p.dkg_round2(&round1_outputs).unwrap())
            .collect();

        // Complete DKG
        let distributed_keys: Vec<_> = participants.iter_mut()
            .map(|p| p.complete_dkg(&round2_outputs).unwrap())
            .collect();

        assert_eq!(distributed_keys.len(), 5);
        
        // Verify all participants have the same public key
        let first_pk = distributed_keys[0].public_key();
        for key in &distributed_keys[1..] {
            assert_eq!(key.public_key(), first_pk);
        }
    }
}
